from __future__ import annotations

from psair.examples.assets import (
    ExampleAssets,
    asset_path,
    get_rendered_docs_path,
    iter_rendered_markdown_files,
    read_yaml_asset,
    read_yaml_specs,
)
from psair.examples.docs import (
    all_workbook_sheet_tables,
    fenced,
    markdown_table,
    preview_json,
    preview_yaml,
    workbook_sheet_tables,
    write_rendered_doc,
)
from psair.examples.files import (
    copy_tree_contents,
    long_path,
    replace_tree,
    scratch_dir,
    write_json,
    write_text,
    write_yaml,
)
from psair.examples.manual import (
    ComposedManual,
    ManualCompositionError,
    ManualSource,
    ManualView,
    build_composed_manual,
    build_composed_manual_index,
    compose_manual_views,
    discover_manual_views,
    split_front_matter,
)

__all__ = [
    "ComposedManual",
    "ExampleAssets",
    "ManualCompositionError",
    "ManualSource",
    "ManualView",
    "all_workbook_sheet_tables",
    "asset_path",
    "build_composed_manual",
    "build_composed_manual_index",
    "compose_manual_views",
    "copy_tree_contents",
    "discover_manual_views",
    "fenced",
    "get_rendered_docs_path",
    "iter_rendered_markdown_files",
    "long_path",
    "markdown_table",
    "preview_json",
    "preview_yaml",
    "read_yaml_asset",
    "read_yaml_specs",
    "replace_tree",
    "scratch_dir",
    "split_front_matter",
    "workbook_sheet_tables",
    "write_json",
    "write_rendered_doc",
    "write_text",
    "write_yaml",
]
